/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_JNITest */

#ifndef _Included_com_example_ndk_JNITest
#define _Included_com_example_ndk_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_JNITest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_JNITest_get
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_JNITest_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    getInstance
 * Signature: ()Lcom/example/ndk/JNITest;
 */
JNIEXPORT jobject JNICALL Java_com_example_ndk_JNITest_getInstance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
