/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_ArraySum */

#ifndef _Included_com_example_ndk_ArraySum
#define _Included_com_example_ndk_ArraySum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_ArraySum
 * Method:    getSum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndk_ArraySum_getSum
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_example_ndk_ArraySum
 * Method:    getSum2
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndk_ArraySum_getSum2
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_example_ndk_ArraySum
 * Method:    get2DArraySum
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_ndk_ArraySum_get2DArraySum
  (JNIEnv *, jclass, jint);



#ifdef __cplusplus
}
#endif
#endif
