/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_NativeLogUtil */

#ifndef _Included_com_example_ndk_NativeLogUtil
#define _Included_com_example_ndk_NativeLogUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_NativeLogUtil
 * Method:    logD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NativeLogUtil_logD
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_NativeLogUtil
 * Method:    logV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NativeLogUtil_logV
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_NativeLogUtil
 * Method:    logI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NativeLogUtil_logI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_NativeLogUtil
 * Method:    logW
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NativeLogUtil_logW
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_NativeLogUtil
 * Method:    logE
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NativeLogUtil_logE
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
